[book]
title = "ssh-obi documentation"
authors = ["Human-life Information Platforms Institute (Menhera.org)"]
language = "en"
src = "docs-src"

[build]
build-dir = "docs"

[output.html]
cname = "obi.menhera.org"
